version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: [sh, -c, 'sleep 10 && python manager.py db upgrade && python main.py']
    # command: [sh, -c, 'sleep 10 && python main.py'] #regular run
    # command: [sh, -c, 'sleep infinity'] #regular run

    
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: [sh, -c, 'sleep 10 && python -u consumer.py']
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
